"""
Deterministic quote fixtures and pure Python reference oracle for Lake Schema v1.

Provides:
- QuoteTick dataclass strictly adhering to Lake Schema v1:
  (timestamp, symbol, price, volume, bid, ask, source, session, ingest_id).
- Schema v1 validator: validate_quote_schema_v1.
- 7 edge-case scenario generators:
  1. Exact duplicates (identical timestamps, prices, fields; different ingest_ids)
  2. Sub-second bursts (microsecond intervals)
  3. Out-of-order / late arrivals
  4. Nulls & Capital quote observation semantics (volume=1.0)
  5. UTC midnight rollover (spans 23:59:59.999999 -> 00:00:00.000000)
  6. NYSE session edges & DST transitions (09:30 open, 16:00 close)
  7. Multi-symbol distribution (NVDA hot 60%, AAPL/MSFT 30%, ADBE/APP 10%)
- Pure Python reference oracle: calculate_expected_candles(ticks, timeframe="1m")
  Independent of DuckDB SQL, breaking ties deterministically by (timestamp, ingest_id).
- Pytest fixtures for all scenarios.
"""
from dataclasses import dataclass
from datetime import datetime, date, time, timedelta, timezone
from typing import List, Dict, Optional, Tuple, Union, Any
import pytest


@dataclass
class QuoteTick:
    """
    Physical representation of a raw quote tick adhering strictly to Lake Schema v1.
    All timestamps are microsecond UTC-naive datetimes.
    """
    timestamp: datetime
    symbol: str
    price: float
    volume: Optional[float] = None
    bid: Optional[float] = None
    ask: Optional[float] = None
    source: Optional[str] = "CAPITAL"
    session: Optional[str] = "REG"
    ingest_id: str = ""

    def __post_init__(self):
        # Normalize string timestamps if provided
        if isinstance(self.timestamp, str):
            self.timestamp = datetime.fromisoformat(self.timestamp)
        # Normalize timezone-aware datetimes to UTC-naive
        if self.timestamp.tzinfo is not None:
            self.timestamp = self.timestamp.astimezone(timezone.utc).replace(tzinfo=None)
        
        # Enforce float types on numeric fields
        self.price = float(self.price)
        if self.volume is not None:
            self.volume = float(self.volume)
        if self.bid is not None:
            self.bid = float(self.bid)
        if self.ask is not None:
            self.ask = float(self.ask)

        if not self.ingest_id:
            # Generate deterministic fallback ID if not supplied
            ts_micro = int(self.timestamp.replace(tzinfo=timezone.utc).timestamp() * 1_000_000)
            self.ingest_id = f"gen_{self.symbol}_{ts_micro}"

    def to_dict(self) -> Dict[str, Any]:
        """Convert tick to dictionary matching lake schema columns."""
        return {
            "timestamp": self.timestamp,
            "symbol": self.symbol,
            "price": self.price,
            "volume": self.volume,
            "bid": self.bid,
            "ask": self.ask,
            "source": self.source,
            "session": self.session,
            "ingest_id": self.ingest_id,
        }

    def to_tuple(self) -> Tuple:
        """Convert tick to tuple matching DuckDB / Arrow ingest row."""
        return (
            self.timestamp,
            self.symbol,
            self.price,
            self.volume,
            self.bid,
            self.ask,
            self.source,
            self.session,
            self.ingest_id,
        )

    def __getitem__(self, item: str) -> Any:
        return getattr(self, item)


@dataclass
class ExpectedCandle:
    """
    Deterministic OHLCV candlestick representation generated by the Python reference oracle.
    """
    time: datetime
    symbol: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    tick_count: int

    def to_dict(self) -> Dict[str, Any]:
        return {
            "time": self.time,
            "symbol": self.symbol,
            "open": self.open,
            "high": self.high,
            "low": self.low,
            "close": self.close,
            "volume": self.volume,
            "tick_count": self.tick_count,
        }

    def __getitem__(self, item: str) -> Any:
        return getattr(self, item)


def validate_quote_schema_v1(tick: Union[QuoteTick, Dict[str, Any]]) -> bool:
    """
    Validates that a tick conforms strictly to Lake Schema v1:
    - timestamp: microsecond UTC naive datetime
    - symbol: non-empty string
    - price: non-null float64 (> 0.0)
    - volume: float64 or None (>= 0.0 if not None)
    - bid: float64 or None (>= 0.0 if not None)
    - ask: float64 or None (>= 0.0 if not None)
    - source: string or None
    - session: string or None
    - ingest_id: non-empty string
    """
    ts = tick["timestamp"] if isinstance(tick, dict) else tick.timestamp
    sym = tick["symbol"] if isinstance(tick, dict) else tick.symbol
    price = tick["price"] if isinstance(tick, dict) else tick.price
    vol = tick["volume"] if isinstance(tick, dict) else tick.volume
    bid = tick["bid"] if isinstance(tick, dict) else tick.bid
    ask = tick["ask"] if isinstance(tick, dict) else tick.ask
    source = tick["source"] if isinstance(tick, dict) else tick.source
    session = tick["session"] if isinstance(tick, dict) else tick.session
    ingest_id = tick["ingest_id"] if isinstance(tick, dict) else tick.ingest_id

    if not isinstance(ts, datetime) or ts.tzinfo is not None:
        raise ValueError(f"Schema v1 error: timestamp must be UTC-naive datetime, got {type(ts)}: {ts}")
    if not isinstance(sym, str) or not sym:
        raise ValueError(f"Schema v1 error: symbol must be non-empty str, got {sym}")
    if not isinstance(price, (float, int)) or price <= 0.0:
        raise ValueError(f"Schema v1 error: price must be positive float64, got {price}")
    if vol is not None and (not isinstance(vol, (float, int)) or vol < 0.0):
        raise ValueError(f"Schema v1 error: volume must be None or >= 0.0, got {vol}")
    if bid is not None and (not isinstance(bid, (float, int)) or bid < 0.0):
        raise ValueError(f"Schema v1 error: bid must be None or >= 0.0, got {bid}")
    if ask is not None and (not isinstance(ask, (float, int)) or ask < 0.0):
        raise ValueError(f"Schema v1 error: ask must be None or >= 0.0, got {ask}")
    if source is not None and not isinstance(source, str):
        raise ValueError(f"Schema v1 error: source must be str or None, got {source}")
    if session is not None and not isinstance(session, str):
        raise ValueError(f"Schema v1 error: session must be str or None, got {session}")
    if not isinstance(ingest_id, str) or not ingest_id:
        raise ValueError(f"Schema v1 error: ingest_id must be non-empty string, got {ingest_id}")

    return True


# ============================================================================
# 7 EDGE-CASE SCENARIOS
# ============================================================================

def generate_exact_duplicates(symbol: str = "AAPL", base_time: Optional[datetime] = None) -> List[QuoteTick]:
    """
    Scenario 1: Exact Duplicates
    Generates ticks where timestamps, prices, and all metadata are identical,
    differing only in their unique ingest_ids.
    Preserves multiple duplicate clusters (pairs and triplets).
    """
    if base_time is None:
        base_time = datetime(2026, 10, 2, 14, 30, 0, 123456)

    ticks: List[QuoteTick] = []

    # Duplicate Pair 1 (identical timestamp, price, bid, ask, volume)
    ts1 = base_time
    for i in range(2):
        ticks.append(QuoteTick(
            timestamp=ts1,
            symbol=symbol,
            price=150.25,
            volume=100.0,
            bid=150.20,
            ask=150.30,
            source="CAPITAL",
            session="REG",
            ingest_id=f"dup_pair1_seq{i}",
        ))

    # Distinct non-duplicate tick
    ticks.append(QuoteTick(
        timestamp=base_time + timedelta(seconds=5, microseconds=100000),
        symbol=symbol,
        price=150.40,
        volume=50.0,
        bid=150.35,
        ask=150.45,
        source="CAPITAL",
        session="REG",
        ingest_id="distinct_tick_01",
    ))

    # Duplicate Triplet (3 ticks with exact same timestamp and fields)
    ts2 = base_time + timedelta(seconds=15, microseconds=654321)
    for i in range(3):
        ticks.append(QuoteTick(
            timestamp=ts2,
            symbol=symbol,
            price=150.50,
            volume=75.0,
            bid=150.45,
            ask=150.55,
            source="CAPITAL",
            session="REG",
            ingest_id=f"dup_triplet_seq{i}",
        ))

    # Duplicate Pair 2
    ts3 = base_time + timedelta(seconds=30, microseconds=999999)
    for i in range(2):
        ticks.append(QuoteTick(
            timestamp=ts3,
            symbol=symbol,
            price=150.10,
            volume=200.0,
            bid=150.05,
            ask=150.15,
            source="CAPITAL",
            session="REG",
            ingest_id=f"dup_pair2_seq{i}",
        ))

    return ticks


def generate_subsecond_burst(symbol: str = "NVDA", base_time: Optional[datetime] = None, count: int = 50) -> List[QuoteTick]:
    """
    Scenario 2: Sub-second Bursts
    Generates a burst of microsecond-spaced ticks within a single second window.
    Tests microsecond precision, tie-breaking, and fast ingest throughput.
    """
    if base_time is None:
        base_time = datetime(2026, 10, 2, 14, 30, 0, 0)

    ticks: List[QuoteTick] = []
    # Distribute ticks evenly across 0 to 999,900 microseconds within that exact second
    step_micros = 999_900 // max(count, 1)

    for i in range(count):
        ts = base_time + timedelta(microseconds=i * step_micros)
        # Small price oscillation around 120.00
        p = 120.0 + round((i % 7) * 0.05, 4)
        ticks.append(QuoteTick(
            timestamp=ts,
            symbol=symbol,
            price=p,
            volume=1.0,
            bid=round(p - 0.05, 4),
            ask=round(p + 0.05, 4),
            source="CAPITAL",
            session="REG",
            ingest_id=f"burst_nvda_{i:04d}",
        ))

    return ticks


def generate_out_of_order_late_arrivals(symbol: str = "MSFT", base_time: Optional[datetime] = None) -> List[QuoteTick]:
    """
    Scenario 3: Out-of-order / Late Arrivals
    Generates a sequence of ticks where the physical arrival order differs from
    the event timestamp order (e.g. late network packets or provider reordering).
    The reference oracle and parquet lake must sort deterministically.
    """
    if base_time is None:
        base_time = datetime(2026, 10, 2, 14, 30, 0, 0)

    # Chronological timestamps spanning 60 seconds
    t0 = base_time                                           # 14:30:00
    t1 = base_time + timedelta(seconds=10)                  # 14:30:10
    t2 = base_time + timedelta(seconds=20)                  # 14:30:20
    t3 = base_time + timedelta(seconds=30)                  # 14:30:30
    t4 = base_time + timedelta(seconds=40)                  # 14:30:40
    t5 = base_time + timedelta(seconds=50)                  # 14:30:50
    t_late1 = base_time + timedelta(seconds=5)              # 14:30:05 (arrives late)
    t_late2 = base_time + timedelta(seconds=15)             # 14:30:15 (arrives late)

    tick_map = {
        "t0": QuoteTick(t0, symbol, 420.0, 10.0, 419.9, 420.1, "CAPITAL", "REG", "arr_t0"),
        "t1": QuoteTick(t1, symbol, 420.5, 15.0, 420.4, 420.6, "CAPITAL", "REG", "arr_t1"),
        "t2": QuoteTick(t2, symbol, 421.0, 20.0, 420.9, 421.1, "CAPITAL", "REG", "arr_t2"),
        "t3": QuoteTick(t3, symbol, 420.8, 25.0, 420.7, 420.9, "CAPITAL", "REG", "arr_t3"),
        "t4": QuoteTick(t4, symbol, 421.2, 30.0, 421.1, 421.3, "CAPITAL", "REG", "arr_t4"),
        "t5": QuoteTick(t5, symbol, 421.5, 35.0, 421.4, 421.6, "CAPITAL", "REG", "arr_t5"),
        "late1": QuoteTick(t_late1, symbol, 420.2, 12.0, 420.1, 420.3, "CAPITAL", "REG", "arr_late1"),
        "late2": QuoteTick(t_late2, symbol, 420.7, 18.0, 420.6, 420.8, "CAPITAL", "REG", "arr_late2"),
    }

    # Physical arrival sequence with late arrivals placed near the end
    arrival_order = ["t0", "t2", "t1", "t4", "t3", "t5", "late1", "late2"]
    return [tick_map[key] for key in arrival_order]


def generate_null_and_capital_quotes(symbol: str = "AAPL", base_time: Optional[datetime] = None) -> List[QuoteTick]:
    """
    Scenario 4: Nulls & Capital Quote Observation Semantics
    Verifies nullable fields (volume, bid, ask, source, session) and Capital's
    quote observation semantics where volume=1.0 represents a price update observation.
    """
    if base_time is None:
        base_time = datetime(2026, 10, 2, 14, 30, 0, 0)

    return [
        # 1. Capital quote observation tick: volume=1.0 with bid and ask
        QuoteTick(
            timestamp=base_time,
            symbol=symbol,
            price=150.10,
            volume=1.0,
            bid=150.05,
            ask=150.15,
            source="CAPITAL",
            session="REG",
            ingest_id="cap_obs_01",
        ),
        # 2. Trade tick: explicit volume, but bid and ask are null
        QuoteTick(
            timestamp=base_time + timedelta(seconds=5),
            symbol=symbol,
            price=150.20,
            volume=500.0,
            bid=None,
            ask=None,
            source="DATABENTO",
            session="REG",
            ingest_id="trade_null_spread",
        ),
        # 3. Quote with null volume (should coalesce to 1.0 in candle aggregation)
        QuoteTick(
            timestamp=base_time + timedelta(seconds=10),
            symbol=symbol,
            price=150.25,
            volume=None,
            bid=150.20,
            ask=150.30,
            source="CAPITAL",
            session="REG",
            ingest_id="quote_null_vol",
        ),
        # 4. Historical tick with null metadata fields
        QuoteTick(
            timestamp=base_time + timedelta(seconds=15),
            symbol=symbol,
            price=150.30,
            volume=None,
            bid=None,
            ask=None,
            source=None,
            session=None,
            ingest_id="hist_all_nulls",
        ),
        # 5. Pure tick: only price and timestamp, all nullable fields None
        QuoteTick(
            timestamp=base_time + timedelta(seconds=20),
            symbol=symbol,
            price=150.35,
            volume=None,
            bid=None,
            ask=None,
            source=None,
            session=None,
            ingest_id="minimal_tick",
        ),
    ]


def generate_utc_midnight_rollover(symbol: str = "NVDA", base_date: Optional[date] = None) -> List[QuoteTick]:
    """
    Scenario 5: UTC Midnight Rollover
    Spans 23:59:59.999999 -> 00:00:00.000000 across UTC day boundary.
    Crucial for testing date partition directory placement (date=YYYY-MM-DD)
    and candle interval boundary continuity.
    """
    if base_date is None:
        base_date = date(2026, 10, 2)

    day1 = base_date
    day2 = base_date + timedelta(days=1)

    return [
        # Ticks on Day 1 leading up to the final microsecond
        QuoteTick(
            timestamp=datetime.combine(day1, time(23, 59, 50, 0)),
            symbol=symbol,
            price=120.0,
            volume=10.0,
            source="CAPITAL",
            session="POST",
            ingest_id="rollover_d1_01",
        ),
        QuoteTick(
            timestamp=datetime.combine(day1, time(23, 59, 59, 500000)),
            symbol=symbol,
            price=120.1,
            volume=10.0,
            source="CAPITAL",
            session="POST",
            ingest_id="rollover_d1_02",
        ),
        QuoteTick(
            timestamp=datetime.combine(day1, time(23, 59, 59, 999999)),
            symbol=symbol,
            price=120.2,
            volume=10.0,
            source="CAPITAL",
            session="POST",
            ingest_id="rollover_d1_edge",
        ),
        # Ticks on Day 2 starting from the exact first microsecond
        QuoteTick(
            timestamp=datetime.combine(day2, time(0, 0, 0, 0)),
            symbol=symbol,
            price=120.3,
            volume=15.0,
            source="CAPITAL",
            session="PRE",
            ingest_id="rollover_d2_edge",
        ),
        QuoteTick(
            timestamp=datetime.combine(day2, time(0, 0, 0, 100)),
            symbol=symbol,
            price=120.4,
            volume=15.0,
            source="CAPITAL",
            session="PRE",
            ingest_id="rollover_d2_01",
        ),
        QuoteTick(
            timestamp=datetime.combine(day2, time(0, 0, 1, 0)),
            symbol=symbol,
            price=120.5,
            volume=15.0,
            source="CAPITAL",
            session="PRE",
            ingest_id="rollover_d2_02",
        ),
        QuoteTick(
            timestamp=datetime.combine(day2, time(0, 0, 30, 0)),
            symbol=symbol,
            price=120.6,
            volume=20.0,
            source="CAPITAL",
            session="PRE",
            ingest_id="rollover_d2_03",
        ),
    ]


def generate_nyse_session_and_dst(symbol: str = "AAPL") -> List[QuoteTick]:
    """
    Scenario 6: NYSE Session Edges & DST Transitions
    Tests market session boundary microsecond edges:
    - 09:29:59.999999 (PRE) -> 09:30:00.000000 (REG)
    - 15:59:59.999999 (REG) -> 16:00:00.000000 (POST)
    Also tests US Daylight Saving Time shift (EST vs EDT):
    - Winter EST (UTC-5): 09:30 ET = 14:30 UTC
    - Summer EDT (UTC-4): 09:30 ET = 13:30 UTC
    """
    ticks: List[QuoteTick] = []

    # 1. NYSE Regular Session Open Edge (Summer EDT: 09:30 ET is 13:30 UTC)
    trading_day = date(2026, 10, 2)
    ticks.extend([
        QuoteTick(
            timestamp=datetime.combine(trading_day, time(13, 29, 59, 999999)),
            symbol=symbol,
            price=150.0,
            session="PRE",
            ingest_id="nyse_open_pre_edge",
        ),
        QuoteTick(
            timestamp=datetime.combine(trading_day, time(13, 30, 0, 0)),
            symbol=symbol,
            price=150.5,
            session="REG",
            ingest_id="nyse_open_reg_edge",
        ),
        QuoteTick(
            timestamp=datetime.combine(trading_day, time(13, 30, 0, 500000)),
            symbol=symbol,
            price=150.75,
            session="REG",
            ingest_id="nyse_open_reg_01",
        ),
    ])

    # 2. NYSE Regular Session Close Edge (Summer EDT: 16:00 ET is 20:00 UTC)
    ticks.extend([
        QuoteTick(
            timestamp=datetime.combine(trading_day, time(19, 59, 59, 999999)),
            symbol=symbol,
            price=152.0,
            session="REG",
            ingest_id="nyse_close_reg_edge",
        ),
        QuoteTick(
            timestamp=datetime.combine(trading_day, time(20, 0, 0, 0)),
            symbol=symbol,
            price=152.1,
            session="POST",
            ingest_id="nyse_close_post_edge",
        ),
    ])

    # 3. DST Transition Check (Winter EST: 2026-01-15, 09:30 ET is 14:30 UTC)
    winter_day = date(2026, 1, 15)
    ticks.extend([
        QuoteTick(
            timestamp=datetime.combine(winter_day, time(14, 29, 59, 999999)),
            symbol=symbol,
            price=140.0,
            session="PRE",
            ingest_id="dst_winter_pre",
        ),
        QuoteTick(
            timestamp=datetime.combine(winter_day, time(14, 30, 0, 0)),
            symbol=symbol,
            price=140.5,
            session="REG",
            ingest_id="dst_winter_open",
        ),
    ])

    return ticks


def generate_multisymbol_distribution(total_ticks: int = 1000, base_time: Optional[datetime] = None) -> List[QuoteTick]:
    """
    Scenario 7: Multi-symbol Distribution
    Generates realistic multi-symbol skew:
    - NVDA: hot 60% (~600 ticks)
    - AAPL / MSFT: 30% (~150 ticks each)
    - ADBE / APP: 10% (~50 ticks each)
    Ticks are interleaved across time in realistic micro-bursts.
    """
    if base_time is None:
        base_time = datetime(2026, 10, 2, 14, 30, 0, 0)

    # Determine symbol counts
    count_nvda = int(total_ticks * 0.60)
    count_aapl = int(total_ticks * 0.15)
    count_msft = int(total_ticks * 0.15)
    count_adbe = int(total_ticks * 0.05)
    count_app = total_ticks - (count_nvda + count_aapl + count_msft + count_adbe)

    symbol_specs = [
        ("NVDA", count_nvda, 120.0, 0.02),
        ("AAPL", count_aapl, 150.0, 0.01),
        ("MSFT", count_msft, 420.0, 0.03),
        ("ADBE", count_adbe, 510.0, 0.05),
        ("APP", count_app, 75.0, 0.01),
    ]

    ticks_per_sym: Dict[str, List[QuoteTick]] = {}

    for sym, count, base_price, volatility in symbol_specs:
        sym_ticks: List[QuoteTick] = []
        for i in range(count):
            # Interleave timestamps across a 600-second (10-minute) window
            time_offset_sec = (i / max(count - 1, 1)) * 600.0
            ts = base_time + timedelta(seconds=time_offset_sec)
            p = round(base_price + ((i % 13) - 6) * volatility, 4)
            sym_ticks.append(QuoteTick(
                timestamp=ts,
                symbol=sym,
                price=p,
                volume=1.0 if sym in ("NVDA", "AAPL") else round(10.0 + (i % 5) * 5.0, 1),
                bid=round(p - 0.02, 4),
                ask=round(p + 0.02, 4),
                source="CAPITAL",
                session="REG",
                ingest_id=f"multi_{sym.lower()}_{i:05d}",
            ))
        ticks_per_sym[sym] = sym_ticks

    # Interleave ticks chronologically across all symbols
    all_ticks: List[QuoteTick] = []
    for sym_list in ticks_per_sym.values():
        all_ticks.extend(sym_list)

    all_ticks.sort(key=lambda t: (t.timestamp, t.ingest_id))
    return all_ticks


def get_scenario_quotes(scenario_name: str, **kwargs) -> List[QuoteTick]:
    """
    Convenience factory to retrieve ticks for any of the 7 edge-case scenarios.
    """
    scenarios = {
        "exact_duplicates": generate_exact_duplicates,
        "subsecond_burst": generate_subsecond_burst,
        "out_of_order": generate_out_of_order_late_arrivals,
        "late_arrivals": generate_out_of_order_late_arrivals,
        "nulls_and_capital": generate_null_and_capital_quotes,
        "utc_midnight_rollover": generate_utc_midnight_rollover,
        "nyse_session_dst": generate_nyse_session_and_dst,
        "multisymbol_distribution": generate_multisymbol_distribution,
    }
    generator = scenarios.get(scenario_name.lower())
    if not generator:
        raise ValueError(f"Unknown scenario '{scenario_name}'. Available: {list(scenarios.keys())}")
    return generator(**kwargs)


# ============================================================================
# PURE PYTHON REFERENCE ORACLE
# ============================================================================

def _parse_timeframe_seconds(timeframe: str) -> int:
    """Parses timeframe string ('1s', '1m', '5m', '1h', '1d') into total seconds."""
    tf = timeframe.strip().lower()
    if tf.endswith("s"):
        return int(tf[:-1])
    elif tf.endswith("m"):
        return int(tf[:-1]) * 60
    elif tf.endswith("h"):
        return int(tf[:-1]) * 3600
    elif tf.endswith("d"):
        return int(tf[:-1]) * 86400
    raise ValueError(f"Unsupported timeframe: {timeframe}. Use '1s', '5s', '1m', '5m', '15m', '1h', '1d'.")


def calculate_expected_candles(
    ticks: List[Union[QuoteTick, Dict[str, Any], Any]],
    timeframe: str = "1m",
) -> List[ExpectedCandle]:
    """
    Pure Python reference oracle that computes deterministic OHLCV candles independently of DuckDB SQL.

    Key guarantees:
    - Normalizes timestamps to UTC-naive datetimes.
    - Floors bucket start time using interval mathematics matching DuckDB time_bucket().
    - Tie-breaks open and close deterministically using (timestamp, ingest_id):
      - open: price of the tick with MIN(timestamp, ingest_id)
      - close: price of the tick with MAX(timestamp, ingest_id)
    - high: MAX(price)
    - low: MIN(price)
    - volume: SUM(coalesce(volume, 1.0)) adhering to Capital quote observation semantics.
    - tick_count: COUNT(*) in bucket.
    - Sorts output by (time ASC, symbol ASC).
    """
    if not ticks:
        return []

    interval_sec = _parse_timeframe_seconds(timeframe)
    epoch = datetime(1970, 1, 1)

    # Group ticks by (symbol, bucket_start_dt)
    buckets: Dict[Tuple[str, datetime], List[Tuple[datetime, str, float, float]]] = {}

    for tick in ticks:
        # Extract fields
        if isinstance(tick, dict):
            ts = tick["timestamp"]
            sym = tick["symbol"]
            p = float(tick["price"])
            vol = tick.get("volume")
            ingest_id = str(tick.get("ingest_id") or "")
        else:
            ts = tick.timestamp
            sym = tick.symbol
            p = float(tick.price)
            vol = getattr(tick, "volume", None)
            ingest_id = str(getattr(tick, "ingest_id", "") or "")

        # Normalize timestamp
        if isinstance(ts, str):
            ts = datetime.fromisoformat(ts)
        if ts.tzinfo is not None:
            ts = ts.astimezone(timezone.utc).replace(tzinfo=None)

        # Capital observation semantics: null volume coalesces to 1.0
        effective_vol = float(vol) if vol is not None else 1.0

        # Calculate bucket floor
        if timeframe.lower() == "1d":
            bucket_time = datetime(ts.year, ts.month, ts.day, 0, 0, 0)
        else:
            total_sec = int((ts - epoch).total_seconds())
            bucket_sec = (total_sec // interval_sec) * interval_sec
            bucket_time = epoch + timedelta(seconds=bucket_sec)

        key = (sym, bucket_time)
        if key not in buckets:
            buckets[key] = []
        buckets[key].append((ts, ingest_id, p, effective_vol))

    candles: List[ExpectedCandle] = []

    for (sym, bucket_time), group in buckets.items():
        # Sort deterministically by (timestamp, ingest_id)
        sorted_group = sorted(group, key=lambda x: (x[0], x[1]))

        open_price = sorted_group[0][2]
        close_price = sorted_group[-1][2]
        high_price = max(x[2] for x in sorted_group)
        low_price = min(x[2] for x in sorted_group)
        tot_vol = sum(x[3] for x in sorted_group)
        tick_cnt = len(sorted_group)

        candles.append(ExpectedCandle(
            time=bucket_time,
            symbol=sym,
            open=open_price,
            high=high_price,
            low=low_price,
            close=close_price,
            volume=tot_vol,
            tick_count=tick_cnt,
        ))

    # Deterministic output ordering
    candles.sort(key=lambda c: (c.time, c.symbol))
    return candles


# ============================================================================
# PYTEST FIXTURES
# ============================================================================

@pytest.fixture
def scenario_exact_duplicates():
    return generate_exact_duplicates()

@pytest.fixture
def scenario_subsecond_burst():
    return generate_subsecond_burst()

@pytest.fixture
def scenario_out_of_order():
    return generate_out_of_order_late_arrivals()

@pytest.fixture
def scenario_nulls_and_capital():
    return generate_null_and_capital_quotes()

@pytest.fixture
def scenario_utc_midnight_rollover():
    return generate_utc_midnight_rollover()

@pytest.fixture
def scenario_nyse_session_dst():
    return generate_nyse_session_and_dst()

@pytest.fixture
def scenario_multisymbol_distribution():
    return generate_multisymbol_distribution()
