#!/usr/bin/env python3
"""
End-to-end reproduction / regression harness for the Tuesday ingestion outage.

It runs the REAL supervisor, the REAL streamer engine and the REAL dashboard
against a lake that already holds migrated ticks, and asks the questions an
operator would ask. The provider is stubbed (no credentials, no network) by a
generated wrapper module, so the engine takes its LIVE code path — the path the
outage happened on — without contacting Capital.com.

Scenarios
  A  live, registry left BLANK by the migration      -> must be LOUD (was silent)
  B  live, registry file MISSING from the lake       -> must be LOUD (control)
  C  live, registry seeded, provider ticking         -> healthy, rows flow
  D  live, registry seeded, provider silent          -> supervisor publishes STALLED
  E  mock, registry blank                            -> lenient by design (dev runs)

Run:  python3 tools/repro_incident.py            (~60s)
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

WORK = Path("/tmp/incident")
RUN_SECONDS = 10.0
STALL_SECONDS = 5.0
DASH_PORT = 8477

# The supervisor launches children as `python -m <module>` with PYTHONPATH set to
# the repo root, so the stub must live there (and is removed afterwards).
STUB_MODULE = "tools._incident_provider_stub"
STUB_PATH = REPO_ROOT / "tools" / "_incident_provider_stub.py"


def write_provider_stub() -> None:
    """A live-path provider stub: ticking or silent, chosen by env var."""
    WORK.mkdir(parents=True, exist_ok=True)
    STUB_PATH.write_text(
        '''
"""Generated by tools/repro_incident.py — live-path provider without network."""
import os


def install():
    from src.stream import runner as r

    class StubProvider:
        def __init__(self, epics=None, on_tick_callback=None, **kwargs):
            self.epics = list(epics or [])
            self.on_tick_callback = on_tick_callback
            self._mock = r.MockStreamer(
                epics=self.epics,
                on_tick_callback=on_tick_callback,
                ticks_per_sec=60.0,
            )

        async def start(self):
            if os.environ.get("INCIDENT_PROVIDER_SILENT") == "1" or not self.epics:
                # Connected, subscribed, but the market never sends anything.
                import asyncio
                while True:
                    await asyncio.sleep(0.5)
            await self._mock.start()

        async def update_subscriptions(self, epics):
            self.epics = list(epics)
            return True

        def stop(self):
            self._mock.stop()

    r.CapitalStreamer = StubProvider
    # The repro must not depend on the wall clock being inside the ET window.
    r.check_ingestion_window = lambda mock_mode=False: (True, "forced open by repro_incident.py")
    return r


if __name__ == "__main__":
    install().main()
''',
        encoding="utf-8",
    )


def http(path: str):
    try:
        with urllib.request.urlopen(f"http://127.0.0.1:{DASH_PORT}{path}", timeout=5) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        return {"__http_error__": e.code}
    except Exception as e:
        return {"__error__": f"{type(e).__name__}: {e}"}


def build_lake(root: Path, mode: str) -> None:
    """mode: 'blank_registry' | 'missing_registry' | 'seeded'"""
    from src.storage.registry import SymbolRegistry, init_registry
    from tests.support.lake_population import create_lake, publish_minutes

    if root.exists():
        shutil.rmtree(root)
    create_lake(root, symbols=["AAPL"])                              # lake + registry + symbol
    publish_minutes(root, session_date=date.today(), symbol="AAPL")  # migrated history
    if mode == "blank_registry":
        init_registry(root, force=True)                              # {"symbols": {}} <- migration state
    elif mode == "missing_registry":
        SymbolRegistry(root=root).path.unlink()

    reg = SymbolRegistry(root=root)
    active = len(reg.get_active_symbols()) if reg.path.exists() else "n/a (file gone)"
    print(f"  registry: exists={reg.path.exists()} active_symbols={active}")


def run_stack(lake_root: Path, tag: str, *, mock: bool, silent: bool, stall_seconds: float = 900.0) -> dict:
    log_dir = WORK / f"logs_{tag}"
    if log_dir.exists():
        shutil.rmtree(log_dir)
    log_dir.mkdir(parents=True, exist_ok=True)

    env = os.environ.copy()
    env["TICK_LAKE_ROOT"] = str(lake_root)
    env["PYTHONPATH"] = str(REPO_ROOT)
    env["NOTIFICATIONS_DISABLED"] = "1"
    env["SKIP_DISCORD"] = "1"
    env["INCIDENT_PROVIDER_SILENT"] = "1" if silent else "0"
    # match the dashboard's degradation threshold to the supervisor's stall
    # threshold so the scenario completes inside the harness runtime
    env["NO_PROGRESS_SECONDS"] = str(max(stall_seconds, 8.0))
    env["DASHBOARD_PORT"] = str(DASH_PORT)

    module = "src.stream.runner" if mock else STUB_MODULE
    child_args = ["--mock", "--lake-root", str(lake_root)] if mock else ["--lake-root", str(lake_root)]
    sup = subprocess.Popen(
        [sys.executable, str(REPO_ROOT / "tools" / "service_supervisor.py"),
         "--name", "streamer", "--module", module,
         "--log-dir", str(log_dir), "--poll-interval", "1", "--watch", "src",
         "--watch-ingestion-progress",
         "--stall-seconds", str(stall_seconds),
         "--heartbeat-log-interval", "60",
         "--args", *child_args],
        env=env, cwd=str(REPO_ROOT), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    dash = subprocess.Popen(
        [sys.executable, "-c",
         "import sys; sys.path.insert(0, %r);"
         "from src.dashboard.server import run_dashboard_server as run;"
         "sys.argv=['server']; run()" % str(REPO_ROOT)],
        env=env, cwd=str(REPO_ROOT), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    time.sleep(RUN_SECONDS)
    obs = {"supervisor_alive": sup.poll() is None}

    obs["api_status"] = http("/api/status")
    obs["api_symbols"] = http("/api/streaming/symbols")
    obs["api_integrity"] = http("/api/integrity")

    sp = log_dir / "streamer.state.json"
    try:
        obs["lifecycle"] = json.loads(sp.read_text())["state"]
    except Exception:
        obs["lifecycle"] = "<none>"

    wp = lake_root / "_control" / "writer_status.json"
    if wp.is_file():
        payload = json.loads(wp.read_text())
        obs["writer_status"] = payload.get("status")
        obs["writer_rows"] = payload.get("total_rows_written")
        obs["writer_pid_alive"] = _pid_alive(payload.get("pid"))
    else:
        obs["writer_status"], obs["writer_rows"], obs["writer_pid_alive"] = "<absent>", 0, None

    obs["parquet_files"] = len(list((lake_root / "ticks").glob("symbol=*/date=*/*.parquet")))

    log_path = log_dir / "streamer.log"
    log = log_path.read_text(encoding="utf-8", errors="replace") if log_path.is_file() else ""
    obs["log_bytes"] = len(log)
    obs["ingesting_lines"] = sum(1 for l in log.splitlines() if "Lifecycle: INGESTING" in l)
    obs["stalled_lines"] = sum(1 for l in log.splitlines() if "Lifecycle: STALLED" in l)
    obs["crash_lines"] = sum(1 for l in log.splitlines() if "child exited with code" in l)
    obs["launched"] = sum(1 for l in log.splitlines() if "Launching process" in l)
    obs["refusal_line"] = next(
        (l.split("] ")[-1] for l in log.splitlines() if "Refusing to start live ingestion" in l),
        "<absent>",
    )

    for p in (sup, dash):
        p.terminate()
    for p in (sup, dash):
        try:
            p.wait(timeout=10)
        except subprocess.TimeoutExpired:
            p.kill()
    time.sleep(0.3)
    return obs


def _pid_alive(pid):
    if not isinstance(pid, int):
        return None
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False


def report(title, obs):
    print(f"\n  {title}")
    print(f"    published lifecycle state   : {obs['lifecycle']}")
    print(f"    writer_status.json          : {obs['writer_status']}  rows={obs['writer_rows']}")
    print(f"    parquet files on disk       : {obs['parquet_files']}")
    print(f"    GET /api/status             : status={obs['api_status'].get('status')} "
          f"reasons={obs['api_status'].get('reasons')}")
    sym = obs["api_symbols"]
    print(f"    GET /api/streaming/symbols  : total={sym.get('total')}")
    print(f"    GET /api/integrity          : overall_passed={obs['api_integrity'].get('overall_passed')} "
          f"registry_empty={obs['api_integrity'].get('registry_empty')}")
    print(f"    streamer.log                : {obs['log_bytes']}B, INGESTING lines={obs['ingesting_lines']}, "
          f"STALLED lines={obs['stalled_lines']}, crashes={obs['crash_lines']}")
    if obs["refusal_line"] != "<absent>":
        print(f"    engine refusal              : {obs['refusal_line'][:110]}")


def main() -> int:
    write_provider_stub()
    try:
        return _run_all()
    finally:
        STUB_PATH.unlink(missing_ok=True)


def _run_all() -> int:
    cases = [
        ("A_live_blank", "blank_registry", dict(mock=False, silent=False),
         "A — LIVE engine, registry left BLANK by the migration"),
        ("B_live_missing", "missing_registry", dict(mock=False, silent=False),
         "B — LIVE engine, registry file MISSING (control)"),
        ("C_live_seeded", "seeded", dict(mock=False, silent=False),
         "C — LIVE engine, registry seeded, provider ticking"),
        ("D_live_silent", "seeded", dict(mock=False, silent=True, stall_seconds=STALL_SECONDS),
         f"D — LIVE engine, registry seeded, provider silent (stall threshold {STALL_SECONDS:.0f}s)"),
        ("E_mock_blank", "blank_registry", dict(mock=True, silent=False),
         "E — MOCK engine, registry blank (dev leniency, by design)"),
    ]

    results = {}
    for tag, mode, kwargs, title in cases:
        print("=" * 78)
        print(title)
        print("=" * 78)
        lake = WORK / f"lake_{tag}"
        build_lake(lake, mode)
        print(f"  running supervisor + streamer + dashboard for {RUN_SECONDS:.0f}s ...")
        results[tag] = run_stack(lake, tag, **kwargs)
        report("observed while running:", results[tag])
        print()

    a, b, c, d, e = (results[k] for k in
                     ("A_live_blank", "B_live_missing", "C_live_seeded", "D_live_silent", "E_mock_blank"))

    print("=" * 78)
    print("VERDICT")
    print("=" * 78)
    checks = [
        ("A  blank registry no longer idles green (loud failure, not INGESTING)",
         a["lifecycle"] == "ERROR" or a["crash_lines"] > 0),
        ("A  /api/status no longer reports HEALTHY for that lake",
         a["api_status"].get("status") != "HEALTHY"),
        ("B  missing registry is loud (control)", b["lifecycle"] == "ERROR" or b["crash_lines"] > 0),
        ("C  seeded lake really ingests", c["lifecycle"] == "INGESTING" and c["writer_rows"] > 0),
        ("C  /api/status HEALTHY when the writer is alive and publishing",
         c["api_status"].get("status") == "HEALTHY"),
        ("D  alive-but-silent writer is published as STALLED, not INGESTING",
         d["lifecycle"] == "STALLED" and d["stalled_lines"] > 0),
        ("D  /api/status degrades on no progress", d["api_status"].get("status") == "DEGRADED"),
        ("E  mock runs stay lenient (documented dev behavior)",
         e["lifecycle"] in ("INGESTING", "STALLED")),
    ]
    for label, ok in checks:
        print(f"  [{'PASS' if ok else 'FAIL'}] {label}")
    return 0 if all(ok for _, ok in checks) else 1


if __name__ == "__main__":
    sys.exit(main())
